POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsaW1tYWtuaSIsImlkIjoiNjQyZGE1MmFhM2VjZDhiNzc5OGU3MzAyIiwiaWF0IjoxNjgwNzIzMTcyfQ.33TwApAmSu64QXq8uwPv1Rv-M-vuD5ct3Sxc63QWHI8

{
    "title": "body building",
    "author": "kamel hachicha",
    "url": "bodybuilding.blog",
    "likes": 2
}