DELETE http://localhost:3003/api/blogs/642db309d75514178e4499d0
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXJoYW1tYW1pIiwiaWQiOiI2NDJkYTUwZmEzZWNkOGI3Nzk4ZTcyZmEiLCJpYXQiOjE2ODA3MjA0Mzl9.n5YJZak1sHxnweqoUuAl5-YCuG2r_LbemEYsbIYwg3A